### ISSUE TITLE
Project is in a folder...

### ISSUE THREAD

**Issue by gstark** [tiy-tpa-ruby/bidtastic-dotrb#7]
At a point where there are no active branches, someone should move *ALL* the files (including any files that start with `.`) into the main folder.

It is unusual to have a Rails application nested in a folder and it will make it difficult to deploy this to Heroku as Heroku expects the project files to be in the root of the repo.

**Comment by pjmiller823** [comment]
Why did it create inside a folder in the first place? I will run fix this later tonight when everyone is off or at a good stopping point with their branches.

**Comment by gstark** [comment]
When you did `rails new name-of-project` you did it *WITHIN* the existing git repository folder.

The empty github repo had documentation on how to turn an existing folder (the one you created from `rails new`) into a git project tied to THIS repo. The step-by-step guide there should have been followed.

When you move the directory do not forget to move the hidden files that start with `.`

Also anyone has a branch they are going to merge may run into issues with a large directory rename such as this. So it may be best to coordinate with everyone when they don't have an outstanding branch. On projects this is often quite difficult to coordinate since it is *rare* that you can get everyone to a state where they have no active branches. In those cases someone just has to be the "I'll help you clean it up" person.

**Comment by pjmiller823** [comment]
Ok thank you.

**Comment by smoline** [comment]
Issue has been resolved.
